### ISSUE TITLE
The "Listen" string and the blue headset icon are barely legible/visible in the "Dark" theme mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/firefox-narrate-experiment#8] opened 2019-02-20 12:28 UTC
**[Affected versions]:**
- Firefox 65 Unbranded
- Firefox 66.0b9 Dev. Edition

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Narrate" add-on (0.3) custom build installed through "about:debugging".
- You are enrolled in the "feature-passive" or "feature-active" branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites. 
2. Navigate to "about:addons" page and enable the "Dark" theme mode.
3. Navigate to the "https://en.wikipedia.org/wiki/Main_Page" website.
2. Observe the "Listen" string and the blue headset icon displayed in the Awesomebar.

**[Expected result]:**
- The "Listen" string and the blue headset icon are correctly displayed and legible/visible.

**[Actual result]:**
- The "Listen" string and the blue headset icon are correctly displayed but barely legible/visible.

**[Notes]:**
- The visibility of the "Listen" string and the blue headset icon becomes even more less visible when the button is hovered.
- Attached are screen shots of the issue:
   With hover effect:
![hoverdarkmode](https://user-images.githubusercontent.com/40061643/53091006-8c8cc100-3519-11e9-9177-30c5e62455c0.png)

   Normal view:
![darkmode](https://user-images.githubusercontent.com/40061643/53091031-98788300-3519-11e9-8c47-e924cc5ab8fe.png)

**Comment by awallin** [comment] 2019-02-20 20:15
@Gozala In dark mode shound't the grey icon and text be displayed?

**Comment by Gozala** [comment] 2019-02-20 20:21
> @Gozala In dark mode shound't the grey icon and text be displayed?

As per our conversation you've decided to use color used by facebook container
https://mozilla.slack.com/archives/CCHSQ4EPR/p1539384936000100

**Comment by awallin** [comment] 2019-02-20 20:23
Ah, that's right. I'll close as won't fix. Matches the current pattern established by Facebook Container.

**Comment by Softvision-RemusDranca** [comment] 2019-02-21 16:16
Following and retesting this issue it seems to be a difference between "Facebook container" icon and "Narrate" icon in size and also in color. Considering this I will reopen the issue.
Attached is a screen shot of the issue:
![difference](https://user-images.githubusercontent.com/40061643/53183872-c2f33a80-3604-11e9-81e5-e9d56df8a2c9.png)

**Comment by awallin** [comment] 2019-02-25 20:54
@Gozala Looks like the icon is using the wrong color blue (and might be incorrectly sized) in dark mode. Can you take a look? I've attached the svg with the correct shade of blue if needed.
[Listen icon.zip](https://github.com/mozilla/firefox-narrate-experiment/files/2902556/Listen.icon.zip)

**Comment by Softvision-RemusDranca** [comment] 2019-03-04 13:32
I have retested this issue and it's no longer reproducible for the button's color, the blue font is visible in "Dark" theme mode.
However, it seems that the size of the "Listen" button is still considerably smaller than the "Facebook containers" button, regardless of the Firefox theme used, which makes it difficult for users to read. 
Considering this, I will reopen this issue.

**Comment by awallin** [comment] 2019-03-06 18:46
@Gozala Can you try this one?

[Listen-with-label.svg.zip](https://github.com/mozilla/firefox-narrate-experiment/files/2937818/Listen-with-label.svg.zip)

**Comment by Gozala** [comment] 2019-03-12 23:46
Fixed by 3e06d03

**Closed by Gozala** 2019-03-12 23:46 UTC
Labels: [QA]:Major issue

**Comment by Softvision-PatriciuPop** [comment] 2019-03-14 15:35
I have verified that this issue is no longer reproducible using firefox-listen-study@shield.mozilla.org-0.7-signed-testing.xpi on Windows 10 x64 and Mac 10.14.3 using Firefox Unbranded Beta Version 66.0b14, Build ID 20190307095232.
